name: CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'

      - name: Build
        run: nimble build -y

      - name: Run tests
        run: nimble test

      - name: Install emscripten
        uses: mymindstorm/setup-emsdk@v11

      - name: Build for web
        run: nimble wasm

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web
          cname: gba.mattrb.com
          force_orphan: true
